name = "tfnp"
version = "0.1.0"
defaultTargets = ["Tfnp"]

[leanOptions]
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "6cf3ab1c11e19e328c2e535bdd32d66dc7842fb5"

[[lean_lib]]
name = "Tfnp"
globs = ["Tfnp.*"]
